### PR TITLE
Fixed the glitch dockerized version

### PR DESCRIPTION
**Pull request by fruitl00p**
It might be a bit ugly, but due to the comment from @scato that the code cannot look outside the `/var/app` root we pre-symlink the names file during build to it so when running it like:

 ```
 docker run -v $(the-names-location-on-the-host):/var/names scato-glitch
 ```
 everything should work :)

This fixes the issue #94

### CODE REVIEW

**Comment by lucasvanlierop** [comment]
Great work!

@scato thanks for your help!

**Comment by fruitl00p** [comment]
@lucasvanlierop the test failed since it seems to work differently than i expected: /var/names/current? or /var/names ? what's the deal? :)

(could it be that the dockerfile CMD should be a simple `CMD ["php", "/var/app/vendor/bin/glitch", "raffler.g", "names/current"]` ?

**Comment by lucasvanlierop** [comment]
it should be `/var/names/current` because `/var/names` is the dir with all names and `current` a symlink` to the file which should be raffled. However I think it's possible to mount just the file instead of the whole dir. That would be an improvement.

**Comment by fruitl00p** [comment]
@lucasvanlierop that fixed it.. simple update of the run command fixed it!

**Comment by lucasvanlierop** [comment]
nice :-)

**Pull request merged**
