### PR TITLE
Jaytaph saffire

### PR DESCRIPTION
**Pull request by jaytaph**

### CODE REVIEW

**Comment by ramondelafuente** [comment]
work-in-progress

**Comment by rosstuck** [comment]
Hah, cool! :smile: Do you want us to merge it or should we wait until the lang supports all the features?

**Comment by jaytaph** [comment]
I think it a few more hours, and I have the last method (`.lines()` implemented)..  @ramondelafuente is testing as we speak :p

**Comment by ramondelafuente** [comment]
This baby rrrrrrrollllls!

saffire-wow

**Comment by rosstuck** [comment]
sapphire

**Pull request merged**
