### PR TITLE
PHP(7) Extension

### PR DESCRIPTION
**Pull request by jaytaph**
So yeah, seems we were missing a PHP extension...

### CODE REVIEW

**Comment by dennisdegreef** [comment]
As a feature request, this would be nice... :trollface: 
```
string domcode_logo_guid ( void )
```

**Comment by jaytaph** [comment]
Provide the image (base64 gif prefered, and it shall be done)

**Comment by dennisdegreef** [comment]
```
R0lGODlhyADIAPcKADMqJyELCyIMDCEMDCMNDe0cJO4sJ/F8X0AuLf7j1/////FROfzGsfecf//+/rFpWJOFhDYjHy8bGVpFN6CIYdW3duLBeWtVQiILC6ePZSQQD/TajF9KO6+WaenOhPfdjtC3eyYTE0AsJrSba97EgSsXFebGfXZgSbqhb+zRiEo2LYNsUcCkbfDViTYtKkRKRFRnXlFiWWORhE86MJqEX5F6WSgWFWiomU9cVFt7bz8+Oi4hHzw6NmGMf2u7rGzHti8jISwdHMWpcGNQPl6BdUhSS0lbUlVBNGq2p1ZtY0dNR2zDs2aekEFDPmOUhzIfHFdwZkdHP2mzpFp1ajo2MWWajGzFtXplTFE+M5Z+XMmwd9+/ede9foZxVOLJhGy+r0tUTmmtno11VUYyKigbGl+HejgyL2eklW5cSLWicWSZixscG088MVt+cr6mcktlW0xqX01vY0uhkE95bDEnJE6PgE2cjUufj0+CdU2Whl+GeWnAsGe7q2CyolqqmmK1pWO2p1ytnWW5qWe9rV6EeE6EdlCAc0+MfVE8MVRANJyUeSckJSMfIHFwbVNTVJ+hpHx+gbO1t8rLzZqcnr7Awu/w8OLj5IiKjNfY2oOEh4yOkd7g4VeajKeprAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAADIAMgAAAj+AAEIHEiwoMGDCBMqXMiwocOHECNKnEixosWLGDNq3Mixo8ePIEOKHEmypMmTKFOqXMmypcuXMGPKnEmzps2bOHPq3Mmzp8+fQIMKHVoxgICjSJMKGBCAqFOYBJRKRfq0KsujBbJq1WrgAAIBVsOixLpV64EECr6KXUuS7NYFDBTIVcu27ke3BQw0cCB3Lli7gDe6Pdu3L93AiC1ihVu48OHEkCMefQChsuXLEf5G3uxwwFSpAziLZug5gOnTqE2PXp3QM+vXEV3Dnk1aM+3bBo3i3l3waFPeu40uBb5bgIQJAn4Th+2ZQgUBBJbPFhDBgoULyaWzxiAgg/UKGmz+a99M3bqFDRyyj9/MvYN1Dx9AhBC/PrAAEeY3fPiAPXR9xEeN8N5+H5BQgnr/VcWUZ0nhZ4EJBO53glIBYKBcgjqd9tlRKFiXQoQfeCDBhr5hSBNTJCKlgnUQgvjBCikixZSJLAkXIwHhsWBdCy5+0EJm88WY3IU0hhRAVBsS4MILMMQgAwwCzMDifiTQAGINAthwAw454KDDDjH6V2RHDE6lAQ8x9ODDDz/4AIQOQQgghHX6fTCEBCREuIEIAuggABFs/nBDDkUAQCKRY1KE4lRBFEHEmoGyaQRSRwz4wQhHTQAiBdAJsAMSkbJ5QxI8hDcVBokqWmZSNijRwxL+kTLRhBM/MGGqnHT6yOdRGYD4BFJKtAlFFKFKMQUVSFKY6kOmTUXFFJCGWoUAQFhBhQBXYCFAFhbA96IAJSAXgbcfaBHeEEfJ0IMALoQa6JZxSoXqsgqZGUUV7kY6LRBTCPDEFuBpUMF+XBzYhRe/XrDfBipE+UF6AKzbbr5sfpGDC1OJSe9ANiIVAhhhUKwvtXEKaAGWT4hRwxgCjKEfpwRcsMIRAoSgRYEjvsCuyJH2cK1SM24cwKoCaKBEyDwHOu18lZqXmQ1kQIcCgTRrQEZ4JxCYRacTJ81mGWZIhSiN3Cmlwxlej1x0BSyYEYUHW+MowBAfoOFCGgXXTF3+Cl0A0OsMR3WdthU5ACFvoh2D1UPaoapxlBgnr7GGFx+wcZQElAOwxhUfiIFUrzysQbd8njIeqQ84BInUvBgmrgEOX5geaRvGfXeClfHZsO1+HZxAOcMCaPqBG2hwsR+6Icge6Rk/IzW2dIm7wITyswvQdLcRrqBCnSBqIYHxLnaRJfWBWpGE7kk9z1vHBBgRO/lsTsuBdVt0MYYIJ6SwAQgfbCDG/WigXHw+kAUViOACefpAB3YGPzadAWPpG0+yBBCExTUwfsGzwBZohpQxfMhODRIgGpISgTwtUHDw+wIYgLacsiHFDEi74A+mNQELeE4DRniD7jiXAegYAQ7+UUPDB1BwlCLEIU50O6EMA9UG9JVofUpRwvuWSEMLAE4JcpDDG6jzAeQ0IYtwMM4G0MWDLM6hZilQ4hLZxAQ6RBA3iYPBGpVmPQv8ag5ZrMNRUsCnOGTRDkfhAsvgkMU76E4LapyjFMImo9t0TANtmCMdpXQgPGQxD0fxQmbwmMWjgKCPWZQDmNyQyDn6oAlJiQ5sOhYCC0pyhlGyQCUvmclNhtKToMziKEs5xyUoISkaE03HbCCDV05SlgKwpBwwKQBNCoCTcsClAPyoSwGQkoHGtEIRgLmaYdLKmBikZDJp2UxbdlIAn5xmKHeJTXBu03mjSUorwXnMWS6zls/+vCU6cylKa/LylVb4ZSM3UyYC6IGe9RznPcuZz3Omk5r9vCYKjbkEVA40MUqBAkITqkxmOhOa0oQoOydqzC80D0GA6ZgRNspRcn5Unw9dpz/biVApuJEqgVmVDqzA0nAis6P4BOk+1VlNifbUgU4M5lqSQgdQHXVa4gQqQ4Ua06L+E6FESArrluqx6R0VllF1qTmjOVSRzpSkCJ3U6tjSMY1+Faw/FWtDyVrViF4VoUtg5FHYkhQdvNWn9vToWEMqU6P+9QxJFUtSgiCFv8I1sEGFKT9HmrQ98OGymM2sZjeb2T0Eql8XdYoLBZADxz5WoYKdK2GtSlN39cEPsI3+rWxnS1vZ/qF8PECKKp9SJr+aFqpxXehLHTrZsybttbVNrnL7EKkbqE59PSlTCG5g2tNKdbh0La5hRYZc5XpXtsyNVAyS8pSk4KC61pUrVbV710B197vfvW2kvnDT4QylTECIlmOBC9mpSpaodm1tqPYAiAIb+MAITvCBPRuqrOJUKEmZAnphuaL+Yne1AUbrV5unVJ6UCQCwQu+0xhDc1K4XwJSd8Loe/JOklHbCIy5xZImLYuOajg9/yLGOd8zjHu+YwT/I7RN98mGewrhlMvYvjc263bQFAr5QFkSgZEDeFiNFwhOGJYktPNiyFra9+XoylL8r5UDpFbo0cWH+EKYoYiRzWbVeZq2GwzxmMlePxRlCSgyyjMEto3bG2a1xk70m5jonlw+RWoLhjrLVnOg2hkf2sxHiEIcwMtSIlJamEigdh6gNurKDCLWoR03qUo/ayIEa75BzYiPf8jnGB5KKM6WSTql8urphSBZPkgUoPmvZAvcTgbCH7QU2DPvYXJjAsYeNSAFX10+rvglSyMDmSE+pR9jONpj/mgN4shopL/B1n60jBBBxgUc92gD4CEQC+Gz7rUhQnU6SVQZx/9oCERjDulcggS64KAMR4ECEJqABNyjQ2dW1KEprghQbVNva+LYmgWAkcBBRPEIHMvi73wrahc+k1fa+d2b+DL6fi1tcABXfT8YPPmfHhqHKNimTW8Ud44iT/FspnzjKMS7xjb8VgvSRSVLQZu+aj1znOS/5zgm0cp9/dYVH6TBMkBIExllhD1jPuta3znWth5hiRpe40pOOc55rHOHVJYS3T4SUJjDuD4ZeLs/W9QQKZGFEKjiC3vkUAb37/Qh8/3t48t4wIIT8B1KA+ceRIse0vTfu4OVZt4VEeXke/gf1tYmNXHlcyNc2vBQrA3WykAUxcOD0qE+96lefestV/fAKl3pLktLYtMHd87MFfb6A+6Bs+95FTv+qqu07E6TswHSD6IPyl8/85juf+YgWGe8hlIIPgqgF5IpQ9SP+FPyjqj3qDD8KFS7PexZgISpjmNp+QHCE8IigAwTSAhvQr/7u9/QMuqWJjcJ9eOAKYUQeMzUkkBlIoQEj8AFcAIBHEQJn13Km9QW6tnhHsWc8sweCcIEYmIEauIEZCGRJA1zoQgeFUAdhwwYfMCE7YAh1cC0qwB8CIIKHEDZYwHKX9wOLFnQtYSNYxl24N1vy5TXAhQgC8AZZZAhcRDNGUITG8QENQ4RycEYRQIOX1zxphhT1xjOPh3u6xzNBOIRZhAdclAgCkIRyAIYlwIRe+IRcZH89pXA0kRTfxIM9GFtbKH2xJIROCIZRKIZkaIZo6IRQKIWHJ1AeN3tIQV3+WDiHsfWDH3iHaaiHH8CHXwguf2hGa4h26IUDazd1SOFUImOBHBiKouiBXOiIeRiGYziJZ9iElhiFbMhSUBJtLpEUnlh0pjiJe5iKZUiJrKiGroiJ1RWLhXgVSFGDXXiKudiHvJiGgfiKG5UEm/gSSWGMt7iLyaiKleiLghhyHSd7KjGN5FeNkCiJu7iKzHiJDmhaUBCNs4gU+kVz4oiKymiOgIiONSiMaDYWnRiOUoKHuBiJuuiHvdiMwGha+Fh8SAFp8NiPjyiP2DiQ9nh5miiLOYgUXhVyx/iPiUAGTdAEOqAEZBAE2UiQ6ehY70R8MFEmnLeQFuCP1qgIi8D+CDI5k4zQCBD5iyX5V24ogQIQSf0njtEhk47wCJDgCJHQCDLpAhpQjzhZg0KGgyxRJo2HkeJIBoywCI/QGAogCTwgk0y5jfZmKHs1Ey5UBPzYkmloCDI5CX1BCWBQCXIhCTEZA60IluImb294FK5miwzphEnACI5QGI/ACJbQF5fACC9Ql85ITy+HZ5wIFmfpkmDACFnZF4NZmHKBCVd5B9q4mOBEZRTZjtDxjq9WjU3ACJlQGJrACJBwCZewCZQQk5zQmQX5V9AYmi1RJmrwk32ZRTrACDpQGJBAk5EwnIwwmyR5eYSYjylRJjvIki5ZBIzQCY3BF31hCTJpB7T+mZNfpVeaByy8iZZOCAM1qZWFMQmM8EXbeXhfgJfhB5lU2Zty0AYySQnmqQCW0JU4oJi1+VVOEFoICR21B48r4pJ4IJNmIAlaaQmO4JX8yZ09dZDfeRS9Bo8kZqAEQAdXCQmSQAmNgAmTQAVXGQJf6ZmvBG0oORNlEiy2eKENGQFISZMz6Qg3aZcT5gPuaRNIYXgtKp7/iAVXKZMxuQPAU6L92VMrlqJ5eRQXWZouiowAaQScwAkCeY5NaW9QN4wxYSPnZaE+ao1R+pBWaqPVtQRgMpY4YSN00KMG6pDlOJIR6WugiaY4kRT44msx1qbX+KY1aqJrdJLeuKVIAQb+XqqnYcqnY+qnMvQF8QKVPLlmeIpkhkqOVWqkEEpPkwcdPZEsL5Zlefqih1qpDypuHBZdLxSpT6qRAbmMluprTKB4O5EUxeSpkioARYAHeBBGufgCuBpG5nireLBFV5plOuOY33YUbkerLqoUuagU5sisZPpWYXArQaFbTfpbSMYBEbCt3DoGdsKt3CoCXQSu2+qtigo/WcqcFHGf7MquudF2ynptvzev50o9YaA6jdau+rqv/OquvYEUu+lYkFJzLUIg2eciB0sgifRwPQWoBtGvEBux7WoQScEDpmUGR0OwFhcBYgB8IkB2vLMzYPOcR3UGt9JoACCxKruyCJH+FAf1VxhDBBqbPUtHsyBLg35Csj2FomOzsv4KEmVCBwyLUDE7s0jnIiYHfDuTs3+VpFraE0lBgV9VtEjWezaLtDULIkrEtF9FX7AqFDYSAkR3VIYCBXrQMluQtiCwtms7IUfAtmzrtnALt1sDADeQWzPXUxNJp05RJlSAaiylOpU3uFH0VbbCjveVFFMZuITbuEnBoiz1BUAXqEBhIxpwp4wrRPO6udn2K5C7UVn6tBzhs/xaELpGmsYUNZzDBSegAjNwBQnkIzQwAcF2bGOQCCsQuy1QA4mgAkOgfplBqCwlehdFusZ7vIVBEB1DLCyFMRSAArF2FE9wMx3wKyn+UgJZ8AEp0DC65W9iqLOvdAONeiHIW76kWxCrkgTNKwAUwCd08AZGYDhYQDpBoARwwGn4awQ3NQIwEgJFAAe5pQFc8L0b5QNAJx7mm8ARexCWu5KvhDE0cBR1MIkSULd5EEoYHEp3kFtXgBxFUEiGkwEEjFDFGm0KfJ8pwSrXKkkYszUCcMFycAjggiVllME2rDMnQI5yYCgUMMLgNHwCgLJ10TFAoJBz1MJHAcMyXAI0bMM3LAA5rIs7zL4+/EodJ7pi0TEAMKAsvC1JnEVL3MROjME4rMM8XMVzRAS3sluR0TFmUItrhMQvDMYzLAA1PMZZVMZSfMYCAL4X1AP+t+KoKZUUVADHMiTHSlzHd4zHekyGU9zDffxKPSC4lGsXq2IGXHzIXjzHMazIeBxKjRxKfOzH5EMIgquudqEUAGDE8IPIdMzEdvzJeQzFZkzFkbxGbRDIqAwYSgEEK0w+rtzJsLzIYxzKWTTKaySMuCkaq2IDDkw9wRzGsSzLxvzIaEw9vqQswZFKMAC40LzJiTzMsiwH1YzMDRQGJ6WkLHHCpcvAStEEhmw60ezJ1EzLe2zLpOw1TnCmxsrO/pzACJE4dBCHyjPP4lzPUezI5qw8SxADuowQ/xzRx6sQE6QBMfB18gzOryzGn1zO+Ew9N5DOsifRJK2yDBE9mMv+OAbN0Yxszwr90aazBOfDQgpR0ig8oQWIA6hLMSs9zR3t0qIM02nDBOnMxiZCNECQA97M0xotzCxdzEB9zELNM1JQBBOExeMxWuL3zKHS08TsxB4NyfncJjAQNdpML4ljxwTtLl49zmF9zYHyBUnQqIibKkRzFDygB0v9A3JcCIdwCGcEy1Tw14Rd2ISNSlFcBITtRmKdL0gQA/xc10IzFQCQBHAsx86KJZUXxVLR2LFSBE70RhvTGlMRAi/wKmzivCpQAqzd2hMgBE/Q2rI926wtARnQBbQdASAwwlIABXpF06NdG1OxA0XQA87LucjtImKYBFOgA4HMTcENEXfNrVvYYn3JzblawDJXLSO7HN3Km9YFOAYXQAP8c90Iy79HYL2fUck8YdMsGxHg7axjwAEnkAUdoAUkwD16wgVCkAFicAFHEAHbTSG77N4GbuAUcSSDSwCsza0SUAIDviGqEREHXuElfRFD0ykaruFIEuEpwhTdTRAWfuDW+c8bMQCeQQAqrgEq3uIs3uIwftUEYCEbMeILzBqnwR0BoAE8rgGmgeI/7t1CPuREXuRGfuRInuRKvuRM3uRO/uRQHuVSPuVUXuVWfuVYPhoBAQA7```

**Comment by jaytaph** [comment]
Yeah.. this is a problem with PHP7, as the default logo's are removed too..   I would need to basically revert that patch in order to get this working... 

so no...  :-)

**Pull request merged**
