### PR TITLE
rename some stuff, have some fun

### PR DESCRIPTION
**Pull request by ShawnMcCool**
Stupid Requirement

I wanted to make a few changes to this for no reason.

### CODE REVIEW

**Comment by ShawnMcCool** [comment]
More dumb stuff

**Comment by ShawnMcCool** [comment]
This is so stupid

**Comment by ShawnMcCool** [comment]
Maybe they won't make me do this anymore

**Comment by ShawnMcCool** [comment]
...

**Comment by rosstuck** [comment]
Seems legit.

**Pull request merged**
