### PR TITLE
Dockerize aochagavia-rust

### PR DESCRIPTION
**Pull request by lucasvanlierop**

### CODE REVIEW

**Comment by lucasvanlierop** [comment]
@aochagavia I gave it a try yesterday (using the ubuntu 15.10 image I used for other rafflers too) but didn't have enough time to get it working yet.

**Comment by aochagavia** [comment]
Did you try using the Rust image I wrote about in https://github.com/domcode/rafflers/pull/63#issue-129711094? I have no experience with Docker, but it seems that the image comes with Rust included so you don't need to install it through a script.

**Comment by lucasvanlierop** [comment]
Not yet, I'll try to prevent having a totally different base image for each raffler but it must it must. Installing rust isn't the problem btw, it breaks on cargo right now.

**Comment by aochagavia** [comment]
I found [this one](https://github.com/waxzce/rust-docker) which uses Ubuntu as base image :smile:

**Comment by lucasvanlierop** [comment]
@aochagavia It works now, using the image you suggested earlier, I also managed to move the most of the cargo updating and compiling to the image instead of doing it runtime. :-)

**Pull request merged**
