### PR TITLE
Why - for the love of all that is good??

### PR DESCRIPTION
**Pull request by ramondelafuente**
I'm just going to drop this abomination in here:
A raffler, using every single function in PHP that starts with **array\_** exactly one time.

disgust

### CODE REVIEW

**Comment by rosstuck** [comment]
why god

You are a sick, sick, sick man.

I love it.

grinch

**Comment by ramondelafuente** [comment]
Glad you like it :-) This sounded _a lot_ easier than it actually was.

difficult

**Comment by rosstuck** [comment]
No way, this sounds really f'ing hard. Much respect.

**Comment by mitchellvanw** [comment]
If only it was possible to use lambda, then it'd still be really ducking hard.

**Comment by kayladnls** [comment]
just. wow.

**Comment by WyriHaximus** [comment]
Respect!
Respect!

**Comment by jaspernbrouwer** [comment]
What the...?!

what the

**Comment by lucasvanlierop** [comment]
Very very cool!!

**Comment by Seldaek** [comment]
Holy fuck.

**Comment by jaytaph** [comment]
a

**Pull request merged**
