### PR TITLE
Haters gonna hate

### PR DESCRIPTION
**Pull request by jaytaph**

### CODE REVIEW

**Comment by rskuipers** [comment]
I'm worried about you @jaytaph...

**Comment by jaytaph** [comment]
U mad bro?

**Comment by rosstuck** [comment]
yes

**Comment by rosstuck** [comment]
The config file is really what sells it for me!

**Comment by ramondelafuente** [comment]
@rosstuck Stop merging these before we can get a good gififffication going! :-)

**Comment by ramondelafuente** [comment]
@jaytaph you nailed it though.

nailed-it!

**Pull request merged**
