### PR TITLE
Adding haskell example

### PR DESCRIPTION
**Pull request by Sgoettschkes**
Not a haskell pro, but it works. Made it a little smaller than needed to make it more "funky" ;)

### CODE REVIEW

**Comment by rosstuck** [comment]
Sweet! Can you include a little install.sh script showing what you'd need to install on a debian/ubuntu system? :)

**Comment by Sgoettschkes** [comment]
@rosstuck Done :) Is a run script or anything needed as well? You'd need run `runhaskell rafflers.hs path/to/file` to run it without compiling. 

Or compile with `ghc rafflers.hs` and then `./rafflers path/to/file`

**Comment by rosstuck** [comment]
A script is necessary but you can add it or a quick README as a note as you like. :smile_cat:

**Comment by Sgoettschkes** [comment]
@rosstuck There you go.

**Comment by rosstuck** [comment]
You da man! Thanks :dancer:

**Comment by lucasvanlierop** [comment]
Hi @Sgoettschkes 

I just tested this one for the upcoming meetup however there seem to be two issues:
- It doesn't understand Unicode, e.g. "Petra Dreiskämper" becomes: "Petra Dreisk\228mper"
- Sometimes it says: "rafflers.hs: Prelude.(!!): index too large"

Would you mind to take a look at this?, because we would love to use it!

**Comment by Sgoettschkes** [comment]
HI @lucasvanlierop,

thanks for your interest. I digged into your issues and have solved both problems. Please take a look: https://github.com/Sgoettschkes/rafflers/tree/haskell_improvements

* I use the `Data.Text` package to deal with unicode now.
* The index to large was a basic issue with zero based indices. I am taking a random number between 0 and the lenght of the array, which is 1 to big as the positions start at 0.

If you have any issues with the new code, please get back to me!

**Comment by lucasvanlierop** [comment]
Hi, that's fast! Seems to work fine now thanks!

**Pull request merged**
