### PR TITLE
[DONE]The start for the haproxy - phantomjs raffler

### PR DESCRIPTION
**Pull request by BauRo**
This raffler is gonna be nuts!
nuts

### CODE REVIEW

**Comment by BauRo** [comment]
Yep, I did it!
ididit

**Comment by lucasvanlierop** [comment]
I got this error: 

```sh
Acceptance Tests (1) --------------------------------------------------------------------------------
Test find raffler winner (RafflerRunnerCest::testFindRafflerWinner)                             Fail
-----------------------------------------------------------------------------------------------------


Time: 6.59 seconds, Memory: 9.00Mb

There was 1 failure:

---------
1) Failed to test find raffler winner in RafflerRunnerCest::testFindRafflerWinner (/vagrant/Test/tests/acceptance/RafflerRunnerCest.php)
Couldn't see element "h1":
Failed asserting that an array is not empty.

Scenario Steps:
2. I see element "h1"
1. I am on page "/"


FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
Connection to 127.0.0.1 closed by remote host.
==> raffler-server: Destroying VM and associated drives...
==> raffler-server: Removing hosts
==> raffler-server: Running cleanup tasks for 'ansible' provisioner...
cat: winner.txt: No such file or directory
rm: cannot remove ‘winner.txt’: No such file or directory
```

**Comment by BauRo** [comment]
ports

**Comment by BauRo** [comment]
@lucasvanlierop Updated PR, I changed the port range. I tested with 500 names. :-)

**Comment by lucasvanlierop** [comment]
It works!!

INSANE

**Pull request merged**
