### PR TITLE
Add working rust raffler

### PR DESCRIPTION
**Pull request by aochagavia**
@lucasvanlierop Maybe it would be useful to use [this docker image](https://hub.docker.com/r/jimmycuadra/rust/). That way you don't need an extra install script.

### CODE REVIEW

**Comment by aochagavia** [comment]
Closes #63

**Comment by lucasvanlierop** [comment]
Thanks!, I'll use it next meetup :-)

**Comment by aochagavia** [comment]
Awesome! Make sure you have an internet connection when you run it, because the package manager will need to download and compile some dependencies (the random functionality is provided by a library)

**Comment by lucasvanlierop** [comment]
But only the first time right?

**Comment by aochagavia** [comment]
I think so, especially if you don't touch the code

**Comment by lucasvanlierop** [comment]
WIP, see: https://github.com/domcode/rafflers/pull/66

**Pull request merged**
