### PR TITLE
Whitespace entry

### PR DESCRIPTION
**Pull request by mattparker**
Here's a raffler in Whitespace.  Enjoy!

### CODE REVIEW

**Comment by rosstuck** [comment]
We've waited for this moment for a long time. O_O

beaaauutiful

Would you mind adding the original PHP script as well, just so we can show people how it's done in a slightly more...uhhh...readable format? :grinning:

**Comment by mattparker** [comment]
Here you go.  Although I don't understand what you mean by 'more readable'. Hmph.

sno_ani11

**Comment by rosstuck** [comment]
Perhaps more "visible" would've been a better phrasing... ;-)

**Comment by mattparker** [comment]
fargo

**Comment by mattparker** [comment]
More gif's required?

penguin

**Comment by rosstuck** [comment]
# THIS PR IS APPROVED



# RAAAAAAHHHHHHHHHHHHHHH

**Pull request merged**
