### PR TITLE
Add a raffler written in Scala, using Akka

### PR DESCRIPTION
**Pull request by mrook**

### CODE REVIEW

**Comment by lucasvanlierop** [comment]
Cool stuff!, I guess something in the build configuration broke, I'll look into it after today's meetup

**Comment by lucasvanlierop** [comment]
Picking this up again. could you update your PR with master?

**Comment by mrook** [comment]
Done!

**Comment by lucasvanlierop** [comment]
Weird: the docker hub login halts Travis, though it works on master...

**Comment by lucasvanlierop** [comment]
We've fixed the docker issue recently, it turned out to be a security feature of Travis. Can you update again?

**Comment by mrook** [comment]
Done!

**Comment by lucasvanlierop** [comment]
Ah great it's building now, it seems there's an error in the raffler itself though but I guess that's easy to resolve? 

Also, unrelated, it looks like the test is actually building 5 times whereas it should just build once and run 5 times. We should fix that

**Comment by mrook** [comment]
The initial build is actually fine.

However, the line ```git diff --name-only master... | xargs -n1 -I {} find {} -type f | xargs -n1 dirname | grep -vE '\.\.?' | sort | uniq | xargs -n1 -I {} sh -c 'make test RAFFLER={}'``` returns too many results, I've added an additional grep to reduce that.

**Comment by lucasvanlierop** [comment]
@mrook Great!

**Pull request merged**
