### PR TITLE
Pascal

### PR DESCRIPTION
**Pull request by arnovr**
Free Pascal, just because stuff

### CODE REVIEW

**Comment by arnovr** [comment]
better merge https://github.com/domcode/rafflers/pull/125 first, otherwise maybe merge conflicts.

I had a bad branching strategy

**Comment by lucasvanlierop** [comment]
Done, tnx for updating!

**Comment by arnovr** [comment]
Only a merge away to completing, so close and yet so far aeay

**Comment by lucasvanlierop** [comment]
Yes, tnx!

**Pull request merged**
