### PR TITLE
add scala raffler

### PR DESCRIPTION
**Pull request by ShawnMcCool**

### CODE REVIEW

**Comment by rosstuck** [comment]
Can I get an install.sh for this one? :)

**Comment by ShawnMcCool** [comment]
@rosstuck Something like this?

**Comment by rosstuck** [comment]
:+1:

**Comment by Stelian** [comment]
+1

**Comment by rosstuck** [comment]
@ShawnMcCool This PR demands a wacky GIF. Or a shrubbery!

**Comment by rjkip** [comment]
Ni! Ni!

image

**Comment by rosstuck** [comment]
Approved

**Pull request merged**
