### PR TITLE
Another Ansible raffler

### PR DESCRIPTION
**Pull request by breun**
This is the first time I've ever used Docker, so I hope this works.

### CODE REVIEW

**Comment by lucasvanlierop** [comment]
Awesome, thanks!!

**Comment by alcohol** [comment]
But, https://github.com/domcode/rafflers/blob/master/raffle.sh#L21 mounts it on `/var/names.txt` by default. Is `/var/names/current` some symlink?

**Comment by lucasvanlierop** [comment]
@alcohol I changed that yesterday :) https://github.com/domcode/rafflers/commit/a7dec521b315c9e8b37bb28feb913a359c4e6d6c

**Comment by alcohol** [comment]
Derp. My bad.

**Comment by lucasvanlierop** [comment]
Actually I'm happy people keep an eye on this ;), we can use so help in maintaining this project btw ;-)

**Pull request merged**
